version: 0.2
env:
  secrets-manager:
    LOGIN: local/sonar1:sonartoken
    HOST: local/sonar1:HOST
    Organization: local/sonar1:Organization
    Project: local/sonar1:project
phases:
  install:
    runtime-versions:
      nodejs: 14  # Adjust the Node.js version as needed
    commands:
      - echo "Install phase ..."
      - apt-get update
      - apt-get install -y jq
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip sonar-scanner-cli-4.7.0.2747-linux.zip
      - export PATH=$PATH:$PWD/sonar-scanner-4.7.0.2747-linux/bin
  build:
    commands:
      - echo "Build phase ..."
      - ./sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization -Dsonar.java.binaries='**/*.java'
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ; fi
  post_build:
    commands:
      - echo "Post build phase ..."
